CONFIG_S = """language : korean
main_list-how_stat-over_month : True
main_list-last_chap_too_old : True
main_list-show_stat-remaining : True
fail_count_to_force_out : 5
item_list-hq_thum : True
main-sort_on_init-reverse : 1
check_on_open : True
main_list-index-same_len_num : True
main_list-show_stat-delete : True
main_list-show_stat-new_ones : True
main_list-show_stat-last_failed : True
show_read_all : True
main-sort_on_init-option : 3
"""

KOREAN_UI_S = """main-window:"마루마루를 편하게"
main-btn_search:"모두 검색"
main-btn_add:"추가"
main-btn_option:"Settings"
main-label_1:"위 박스에 URL 입력"
main-label-invalid:"올바른 마루마루 URL\\n또는 명령어가 아닙니다."
main-label-success:"추가 성공"
main-label-already:"이미 존재하는 URL"
main-label_1-invalid_form:"잘못된 명령어 형식입니다."
main-label_1-https:"이 프로그램은 https를 사용하는 마루마루를 지원하지 않습니다."
main-btn_add-tooltip:"왼쪽 상자에 마루마루 URL을 입력해 넣은 뒤\\n이 버튼을 누르면 항목이 추가된다."
main-btn_search-tooltip:"'검색에 포함'이 체크된 모든 항목들에 대해\\n검색을 시작한다."
main-lineEdit-tooltip:"이곳에 마루마루 URL을 입력해 넣은 뒤\\n우측의 버튼을 누르면 항목이 추가된다."
main-list_view-tooltip:"만화 리스트가 출력되는 곳.\\n항목을 클릭하면 아랫칸에서 해당 만화가 있는 곳으로 점프한다.\\n안 읽은 챕터 수, 삭제 대기중 등의 상태도 표시된다."
main-progressBar-tooltip:"'모두 검색'을 실행하면 진행 상황이 이곳에 표현된다."
item-btn_open_url:"URL 열기"
item-btn_load:"검색"
item-btn_readall-true:"모두 안 읽음"
item-btn_readall-false:"모두 읽음"
item-btn_delete-true:"삭제 취소"
item-btn_delete-false:"삭제"
item-label-last_update:"마지막 업데이트 : {} 전"
item-label-search_required:"검색을 실행해 주세요."
item-label-delete:"삭제 대기중입니다. 다음 프로그램 시작 시 제거됩니다."
item-label-failed:"마지막 업데이트 실패"
item-check_box:"검색에 포함"
item-check_box_2:"읽지 않은 것만"
item-check_box-tooltip:"이것이 체크 해제돼 있다면 '모두 검색' 대상에서 제외된다."
item-check_box_2-tooltip:"이것이 체크 해제되면 이미 읽은 만화도 우측 리스트에 나타난다."
item-btn_readall-tooltip:"모든 챕터에 대해 '읽음' 표시를 한다."
item-btn_open_url-tooltip:"만화의 메인 페이지를 웹브라우저로 연다."
item-btn_load-tooltip:"만화의 데이터를 웹에서 불러온다."
item-btn_delete-tooltip:"만화에 삭제 예약을 설정한다.\\n삭제 예약된 만화는 다음 프로그램 실행시 삭제된다."
item-graphic_view-tooltip:"썸네일이 표시되는 자리.\\n처음 추가된 만화라면 '검색'을 실행해야 이미지가 나타난다."
item-list_view-tooltip:"챕터 리스트가 표시되는 곳.\\n처음 추가된 만화라면 '검색'을 실행해야 리스트가 나타난다."
item-list_view-read_all:"모두 읽음"
item-list_view-empty:"항목 없음"
item-list_view-new:"새로운 항목!"
misc-time-s:"초"
misc-time-m:"분"
misc-time-h:"시간"
misc-time-d:"일"
misc-time-plural:""
notice-window:"알림"
notice-ok:"확인"
"""

KOREAN_ST_S = """window:"설정"
main-ok:"확인"
main-cancel:"닫기"
main-apply:"적용"
general-tab:"설정"
general-cb_show_read_all:"모든 챕터를 읽은 경우 '모두 읽음' 표시하기"
general-cb_check_on_open:"챕터를 열람할 때 '읽음' 설정하기"
general-label_main_list_view:"메인 리스트"
general-cb_main_list_show_stat_remaining:"읽지 않은 챕터 개수 표시"
general-cb_main_list_show_stat_new_ones:"새로운 챕터 개수 표시"
general-cb_main_list_show_stat_last_failed:"최근 검색 실패한 항목에 표시"
general-cb_main_list_how_stat_over_month:"1개월 이상 검색하지 않은 항목에 표시"
general-cb_main_list_show_stat_delete:"삭제 대기중인 항목에 표시"
general-cb_main_list_show_no_chap_for_awhile:"1개월 이상 새 챕터가 발견되지 않은 항목에 표시"
general-cb_main_list_index_same_len_num:"인덱스 자릿수 일정하게 맞춤"
general-label_item_list_view:"아이템 리스트"
general-cb_item_list_hq_thum:"고화질 썸네일"
general-label_startup:"실행 옵션"
general-label_sort_one_start:"애플리케이션 실행 시 정렬"
general-com_main_startup_sort_opt-0:"정렬 안 함"
general-com_main_startup_sort_opt-1:"제목 순서"
general-com_main_startup_sort_opt-2:"챕터 수 순서"
general-com_main_startup_sort_opt-3:"남은 챕터 수 순서"
general-com_main_startup_sort_reverse-0:"오름차순"
general-com_main_startup_sort_reverse-1:"내림차순"
backup-tab:"백업"
backup-label_backup_save-1:"< 백업 >"
backup-label_backup_save-2:"data 파일을 backup 폴더에 복사해 보존합니다."
backup-btn_backup_save:"백업"
backup-label_backup_load-1:"< 복원 >"
backup-label_backup_load-2:"이전에 백업한 데이터 중에 하나를 선택하여 현재 data에 붙여넣습니다."
backup-btn_backup_load:"복원"
backup-btn_backup_refresh:"새로고침"
backup-notice-success:"미구현"
backup-notice-no_file:"파일을 선택해 주세요."
backup-notice-saved:"저장됨"
info-tab:"정보"
info-line-1:"마루마루 보조자"
info-line-2:"버전 : 1.0.0"
info-line-3:""
info-line-4:"제작자 : 우성민"
info-line-5:"woos8899@gmail.com"
info-line-6:""
"""

SAVE_DATA_S = """6043<0<http://marumaru.in/?m=bbs&bid=manga&p=2&uid=169554<<<<0<True<False<True
%divider%
6855<1<http://marumaru.in/b/manga/16<<<<0<True<False<True
%divider%
"""
